### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by btopro** [btopro/ist402#67]

**Comment by GregOnTech** [comment]
claimed

**Comment by GregOnTech** [comment]
It is a module bundler primarily for JavaScript, but it can transform front-end assets like HTML, CSS, and images if the corresponding loaders are included. Webpack takes modules with dependencies and generates static assets representing those modules. Webpack can take care of bundling alongside a separate task runner. However, the line between bundler and task runner has become blurred thanks to community-developed webpack plugins.
- [SurviveJS official definition](https://survivejs.com/webpack/what-is-webpack/)
- [Webpacks website concepts](https://webpack.js.org/concepts/)
- [Andrew Rays Blog: When to use webpack](https://blog.andrewray.me/webpack-when-to-use-and-why/)
